[project]
name = "ht-videocall-yolov"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiortc>=1.15.0",
    "fastapi[standard]>=0.139.2",
    "lap>=0.5.13",
    "ultralytics>=8.4.104",
    "uvicorn>=0.51.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.411",
]

[tool.fastapi]
system-packages = ["ffmpeg"]
